AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'

Style/SingleLineMethods:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: nested

Style/HashSyntax:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  
Style/SymbolProc:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/WordArray:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/EmptyConditionalBody:
  Enabled: false

Naming/VariableName:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Security/Eval:
  Enabled: false