# 使用 ERB 解析器，並指定 Ruby 解析器版本
AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'

Layout/LineLength:
  Max: 100

Style/Encoding:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

Style/SingleLineMethods:
  Enabled: true