# .rubocop.yml

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'

Style/SingleLineMethods:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: nested

Style/HashSyntax:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false
